73 enh novo módulo faturas de cartão de crédito (#78)
* Dev (#72)

* add instructions to renew certificate https (#63)

* workaround for error: ImportError: cannot import name 'url_decode' from 'werkzeug.urls'

* 59 enh adicionar vinculo e repetição de registros entradas ou saidas ao longo dos meses seguintes (#65)

* repeticao simples de transacao em add transicao

* add logica para remocao de transacao com vinculo e repeticao

* add logica para edicao de transacoes com vinculo e repetiçcao

* add config env var to insert default records

* adjust to config insert-default-records

* ajuste na funcao de importar categorias (#70)

* [enh] - module/menu to add/edit/del credit cards receipts

* [enh] - add/edit/del credit card transactions

* modulo cartao de credito

* add deploy dev

* ajustes ref fluxo, analytics e somatorios corretamente

* ajuste modulo backup/restaur para testes online

* ajuste de rota: add prefix para arquivos utilizando static

* Revert "ajuste de rota: add prefix para arquivos utilizando static"

This reverts commit 2febb23330a7e4d0ef7e1af2e19c5c82e7774592.

* add static route to serve static file in different enviroment