Uat->Prd (#95)
* add deploy ambiente uat

* erro ao criar diretorio, add sudo

* ajuste workflow file

* add chown para access

* adjust bind port

* adjust workflow file

* adjust workflow file: ports

* add ENVIRONMENT in routes; add env var in workflow file

* Dev -> Uat (#94)

* add instructions to renew certificate https (#63)

* workaround for error: ImportError: cannot import name 'url_decode' from 'werkzeug.urls'

* 59 enh adicionar vinculo e repetição de registros entradas ou saidas ao longo dos meses seguintes (#65)

* repeticao simples de transacao em add transicao

* add logica para remocao de transacao com vinculo e repeticao

* add logica para edicao de transacoes com vinculo e repetiçcao

* add config env var to insert default records

* adjust to config insert-default-records

* ajuste na funcao de importar categorias (#70)

* 73 enh novo módulo faturas de cartão de crédito (#74)

* Dev (#72)

* add instructions to renew certificate https (#63)

* workaround for error: ImportError: cannot import name 'url_decode' from 'werkzeug.urls'

* 59 enh adicionar vinculo e repetição de registros entradas ou saidas ao longo dos meses seguintes (#65)

* repeticao simples de transacao em add transicao

* add logica para remocao de transacao com vinculo e repeticao

* add logica para edicao de transacoes com vinculo e repetiçcao

* add config env var to insert default records

* adjust to config insert-default-records

* ajuste na funcao de importar categorias (#70)

* [enh] - module/menu to add/edit/del credit cards receipts

* [enh] - add/edit/del credit card transactions

* modulo cartao de credito

* add deploy dev

* add port 5002 to serve env dev

* add adjustment env for db

* adjust routes file

* 73 enh novo módulo faturas de cartão de crédito (#75)

* Dev (#72)

* add instructions to renew certificate https (#63)

* workaround for error: ImportError: cannot import name 'url_decode' from 'werkzeug.urls'

* 59 enh adicionar vinculo e repetição de registros entradas ou saidas ao longo dos meses seguintes (#65)

* repeticao simples de transacao em add transicao

* add logica para remocao de transacao com vinculo e repeticao

* add logica para edicao de transacoes com vinculo e repetiçcao

* add config env var to insert default records

* adjust to config insert-default-records

* ajuste na funcao de importar categorias (#70)

* [enh] - module/menu to add/edit/del credit cards receipts

* [enh] - add/edit/del credit card transactions

* modulo cartao de credito

* add deploy dev

* ajustes ref fluxo, analytics e somatorios corretamente

* 73 enh novo módulo faturas de cartão de crédito (#76)

* Dev (#72)

* add instructions to renew certificate https (#63)

* workaround for error: ImportError: cannot import name 'url_decode' from 'werkzeug.urls'

* 59 enh adicionar vinculo e repetição de registros entradas ou saidas ao longo dos meses seguintes (#65)

* repeticao simples de transacao em add transicao

* add logica para remocao de transacao com vinculo e repeticao

* add logica para edicao de transacoes com vinculo e repetiçcao

* add config env var to insert default records

* adjust to config insert-default-records

* ajuste na funcao de importar categorias (#70)

* [enh] - module/menu to add/edit/del credit cards receipts

* [enh] - add/edit/del credit card transactions

* modulo cartao de credito

* add deploy dev

* ajustes ref fluxo, analytics e somatorios corretamente

* ajuste modulo backup/restaur para testes online

* 73 enh novo módulo faturas de cartão de crédito (#77)

* Dev (#72)

* add instructions to renew certificate https (#63)

* workaround for error: ImportError: cannot import name 'url_decode' from 'werkzeug.urls'

* 59 enh adicionar vinculo e repetição de registros entradas ou saidas ao longo dos meses seguintes (#65)

* repeticao simples de transacao em add transicao

* add logica para remocao de transacao com vinculo e repeticao

* add logica para edicao de transacoes com vinculo e repetiçcao

* add config env var to insert default records

* adjust to config insert-default-records

* ajuste na funcao de importar categorias (#70)

* [enh] - module/menu to add/edit/del credit cards receipts

* [enh] - add/edit/del credit card transactions

* modulo cartao de credito

* add deploy dev

* ajustes ref fluxo, analytics e somatorios corretamente

* ajuste modulo backup/restaur para testes online

* ajuste de rota: add prefix para arquivos utilizando static

* 73 enh novo módulo faturas de cartão de crédito (#78)

* Dev (#72)

* add instructions to renew certificate https (#63)

* workaround for error: ImportError: cannot import name 'url_decode' from 'werkzeug.urls'

* 59 enh adicionar vinculo e repetição de registros entradas ou saidas ao longo dos meses seguintes (#65)

* repeticao simples de transacao em add transicao

* add logica para remocao de transacao com vinculo e repeticao

* add logica para edicao de transacoes com vinculo e repetiçcao

* add config env var to insert default records

* adjust to config insert-default-records

* ajuste na funcao de importar categorias (#70)

* [enh] - module/menu to add/edit/del credit cards receipts

* [enh] - add/edit/del credit card transactions

* modulo cartao de credito

* add deploy dev

* ajustes ref fluxo, analytics e somatorios corretamente

* ajuste modulo backup/restaur para testes online

* ajuste de rota: add prefix para arquivos utilizando static

* Revert "ajuste de rota: add prefix para arquivos utilizando static"

This reverts commit 2febb23330a7e4d0ef7e1af2e19c5c82e7774592.

* add static route to serve static file in different enviroment

* ajuste das categorias com tipo invertido nos imports; refatoraccao e arquitetura de codigo (#82)

* primeira versao do grafico de controle de gastos

* ajuste categorias com novo campo de meta

* 85 enh adicionar todas as informações ao extrair o backup (#86)

* backup implementado, extração dos dados ok no xlsx

* ajustado restaurar backup com todos os campos da base

* upload_csv fixed

* fix: ajuste grafico top categories para todos meses

* ajuste da funcao normalize e suas particularidades

* 87 enh adicionar campo de pesquisa em transações e transações de cartões de crédito (#88)

* [enh] - add novo comando para limpar banco de um usuário; - também add inicio de uma rota admin, para se implementar coisas futuras a nivel de admin.

* [enh] - add campo de pesquisa em transações e transações com cartão

* 89 enh controle do grafico de categorias meta zerada nao aparece no grafico (#90)

* added chart control from categories page; added filter and sort in categories page

* added tooltip about goals in categories

* 91 enh criar nova pagina envelopes wrapper (#92)

* add envelopes page; add insert-page envelope; add charts envelopes

* implemented envelope edit page; implemented envelope remove page

* roadmap

* fix categories sort

* fix index search+month+year page

* bug:fix farmacia envelope; adjust logic to split string with categories

* empty categories equal default system category name

* wont fix now a bug

* Enh migracao banco postgres (#93)

* Dev (#72)

* add instructions to renew certificate https (#63)

* workaround for error: ImportError: cannot import name 'url_decode' from 'werkzeug.urls'

* 59 enh adicionar vinculo e repetição de registros entradas ou saidas ao longo dos meses seguintes (#65)

* repeticao simples de transacao em add transicao

* add logica para remocao de transacao com vinculo e repeticao

* add logica para edicao de transacoes com vinculo e repetiçcao

* add config env var to insert default records

* adjust to config insert-default-records

* ajuste na funcao de importar categorias (#70)

* Create first-deploy-ec2.yml

* inicio migracao banco postgres

* disable old pipe

* debug to fix deploy

* remove debug

* do not run init-db when container starts

* add ENVIRONMENT var to deploy

* adjust lenght column database

* refactoring before start tests

* update workflow files